language: python
python:
    - "3.6"
services:
    - sqlite
env:
  - global:
      - DJANGO_SETTINGS_MODULE="djangoblog.settings.travis"

install:
  - pip install -r requirements.txt

script:
    - python manage.py test