language: python
sudo: enabled
services:
    - sqlite
python:
    - "3.6"
    global:
     - TRAVIS=true
     - DJANGO_SETTINGS_MODULE="djangoblog.settings.travis"

install:
  - pip install -r requirements.txt

script:
    - python manage.py test

